import Head from 'next/head'
import Navigation from '@/components/Navigation'
import Image from 'next/image'

export default function Home() {

  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>
      <main className='p-4'>
        <div className='flex flex-col items-center'>
          <Image
                src="/images/headShot.jpg"
                height={200}
                width={244}
                className="rounded-lg pb-4"
                alt="profile picture"
              />
          <h1 className='text-xl font-bold'>Grant Licata</h1>
          <h2 className='pt-2 text-center font-medium'>Software Engineer, Project Manager, Mountain Adventurer.</h2>
          <p className='mt-4 text-center'>I'm Grant, a software developer and project manager based in Seattle. A recent graduate of The Coding Dojo's full stack development bootcamp. I hold a passion for learning and working with teams to build great things.</p>
        </div>
      </main>
    </>
  )
}

// I’m Spencer, a software designer and entrepreneur based in New York City. I’m the founder and CEO of Planetaria, where we develop technologies that empower regular people to explore space on their own terms.
